config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :bbqs do
    resources :bookings, only: %i[new create edit update]
  end

  resources :pages, only: %i[my_bbqs]
  resources :bookings, only: %i[index show destroy]

  get "my_bbqs", to: "pages#my_bbqs"
  get "my_bookings", to: "pages#my_bookings"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bbq.rb
class Bbq < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  has_one_attached :photo

  fuel_type = ['Charcoal', 'Electric', 'Gas']
  brands = ['Weber', 'Traeger', 'Big Green Egg', 'Napoleon', 'Yoder Smokers', 'Beefeaters', 'Other']
  grill_size = ["2 people", "4 people", "6 people", "8 people", "10+ people"]

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 50 }
  validates :address, presence: true
  validates :price, presence: true, comparison: { greater_than: 0 }
  validates :brand, inclusion: { in: brands }
  validates :fuel_type, inclusion: { in: fuel_type }
  validates :grill_size, inclusion: { in: grill_size }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bbq

  # Changed default value of start_date to today and removed presence true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :end_date, comparison: { greater_than_or_equal_to: :start_date }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :bbqs

  # User validations for the following are handled via Devise (views/devise/registrations/new):
  #   first_name
  #   last_name
  #   address
  #   email (Devise also handles uniqueness)
  #   password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional parameters in User registration and edit
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name location])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name location])
  end
end

app/controllers/bbqs_controller.rb
class BbqsController < ApplicationController
  before_action :set_bbq, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @bbqs = Bbq.all
    @start_date = params["booking"][:start_date]
    @end_date = params["booking"][:end_date]

    if params[:filters]
      @bbqs = @bbqs.where(brand: params[:filters][:brand]) if params[:filters][:brand].present?
      @bbqs = @bbqs.where(fuel_type: params[:filters][:fuel_type]) if params[:filters][:fuel_type].present?
      @bbqs = @bbqs.where(grill_size: params[:filters][:grill_size]) if params[:filters][:grill_size].present?
      @bbqs = @bbqs.where(pick_up: true) if params[:filters][:pick_up] == "1"
      @bbqs = @bbqs.where(delivery: true) if params[:filters][:delivery] == "1"
      @bbqs = @bbqs.where("price <= ?", params[:filters][:price]) if params[:filters][:price].present?
      markers
    else
      markers
    end

  end

  def show
    @booking = Booking.new
    if params["booking"] && params["booking"][:start_date].present? && params["booking"][:end_date].present?
      @booking.start_date = params["booking"][:start_date]
      @booking.end_date = params["booking"][:end_date]
    else
      @booking.start_date = ""
      @booking.end_date = ""
    end

    @markers = [{
        lat: @bbq.latitude,
        lng: @bbq.longitude,
        marker_html: render_to_string(partial: "marker")
    }]
  end

  def new
    @bbq = Bbq.new
  end

  def create
    @bbq = Bbq.new(bbq_params)
    @bbq.user = current_user
    if @bbq.save
      redirect_to bbq_path(@bbq)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @bbq.update(bbq_params)
      redirect_to bbq_path(@bbq)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bbq.destroy
    redirect_to bbqs_path, status: :see_other
  end

  private

  def set_bbq
    @bbq = Bbq.find(params[:id])
  end

  def bbq_params
    params.require(:bbq).permit(:name, :description, :address, :price, :brand, :fuel_type, :grill_size, :pick_up, :delivery, :dates_unavailable, :photo)
  end

  def markers
    @markers = @bbqs.geocoded.map do |bbq|
      {
        lat: bbq.latitude,
        lng: bbq.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {bbq: bbq}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_bbq, only: %i[create update]
  before_action :set_booking, only: %i[show]

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.bbq = @bbq
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @markers = [{
      lat: @booking.bbq.latitude,
      lng: @booking.bbq.longitude,
      marker_html: render_to_string(partial: "marker")
    }]
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @bbq = @booking.bbq
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_bbq
    @bbq = Bbq.find(params[:bbq_id])
  end

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @booking = Booking.new
    @bbqs = Bbq.all
  end

  def my_bookings
    @bookings = current_user.bookings
  end

  def my_bbqs
    @bbqs = current_user.bbqs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bbqs/_info_window.html.erb
<div>
  <h2><%= bbq.name %></h2>
  <p>Grill Size: <%= bbq.grill_size %></p>
  <h4 class="price"><%= number_to_currency(bbq.price, unit: "£", precision: 2) %> / day</h4>
</div>

app/views/bbqs/edit.html.erb
<h1>Welcome from inside edit view</h1>

app/views/bbqs/index.html.erb
<div class="page-body">
  <div class="index-container">
    <h1>Available BBQs</h1>

    <div data-controller="filter">
      <div class="filter-dates">
        <div data-filter-target="searchDates">
          <% if @start_date.present? && @end_date.present? %>
            <h4 class="date-availability"><%= "#{Date.parse(@start_date).strftime('%-d %b')} - #{Date.parse(@end_date).strftime('%-d %b %Y')}" %></h4>
          <% end %>
        </div>
        <button class="btn btn-outline-secondary" data-action="click->filter#toggle">
          <i class="fas fa-filter"></i> Filter
        </button>
      </div>

    <div id="filter-sidebar" class="filter-sidebar" style="display: none;" data-filter-target="filterBar">
      <div class="filter-header">
        <button id="close-filter" class="close-btn" data-action="click->filter#toggle">✖</button>
      </div>
        <%= simple_form_for :filters, url: bbqs_path, method: :get, html: { id: "filter-form" } do |f| %>
          <div class="row" data-filter-target="reset">
            <%= hidden_field_tag "booking[start_date]", params.dig("booking", :start_date), data: { filter_target: "startDate" } %>
            <%= hidden_field_tag "booking[end_date]", params.dig("booking", :end_date), data: { filter_target: "endDate" } %>
            <div><%= f.input :brand, label: "Brand", prompt: "Select Brand", collection: ['Weber', 'Traeger', 'Big Green Egg', 'Napoleon', 'Yoder Smokers', 'Beefeaters', 'Other'], selected: params.dig(:filters, :brand) %></div>
            <div><%= f.input :fuel_type, label: "Fuel Type", prompt: "Select Fuel Type", collection: ['Charcoal', 'Electric', 'Gas'], selected: params.dig(:filters, :fuel_type) %></div>
            <div><%= f.input :grill_size, label: "Grill Size", prompt: "Select Grill Size", collection: ["2 people", "4 people", "6 people", "8 people", "10+ people"], selected: params.dig(:filters, :grill_size) %></div>
            <div><%= f.input :price, label: "Max Price", placeholder: "Enter max price", input_html: { value: params.dig(:filters, :price) } %></div>
            <div><%= f.input :pick_up, as: :boolean, label: "Pick-up Available", input_html: { checked: true }, input_html: { checked: params.dig(:filters, :pick_up) == "1" } %></div>
            <div><%= f.input :delivery, as: :boolean, label: "Delivery Available", input_html: { checked: params.dig(:filters, :delivery) == "1" } %></div>
          </div>
          <div class="text-center mt-3">
            <%= f.submit "Apply Filters", class: "btn btn-primary", data: { action: "click->filter#submit" }%>
            <%= link_to "Reset", bbqs_path( booking: { start_date: params.dig("booking", "start_date"), end_date: params.dig("booking", "end_date") }), class: "btn btn-secondary", data: { action: "click->filter#reset" } %>
          </div>
        <% end %>
      </div>

      <div class="index-bbq-map-container" data-action="click->filter#close" data-filter-target="removeSidebar">
        <div class="index-bbq-container">
          <% @bbqs.order(:name).each do |bbq| %>
            <a href="<%= bbq_path(bbq, booking: { start_date: params.dig("booking", "start_date"), end_date: params.dig("booking", "end_date") }) %>" class="cards-horizontal-link">
              <div class="cards-horizontal">
                <% if bbq.photo.attached? %>
                  <%= cl_image_tag bbq.photo.key, height: 430, width: 1000, crop: :auto, alt: "#{bbq.name} image", class: "cards-horizontal-image" %>
                <% else %>
                  <%= image_tag "bbq.png", height: 430, width: 1000, crop: :auto, alt: "#{bbq.name} image", class: "cards-horizontal-image" %>
                <% end %>
                <div class="cards-horizontal-card-info">
                  <h2><%= bbq.name %></h2>
                  <p class="truncate-text-lines"><%= bbq.description %></p>
                  <h4 class="cards-horizontal-price"><%= "#{number_to_currency(bbq.price, unit: "£", precision: 2)} / day"  %></h4>
                </div>
              </div>
            </a>
          <% end %>
        </div>

      <div class="index-map-container">
        <div class="map-one" style="width: 100%; height: 400px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">

        </div>
      </div>
    </div>
  </div>
</div>

app/views/bbqs/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3 class="add-bbq-header">List your BBQ for rental</h3>
        <%= simple_form_for @bbq do |f| %>
          <%= f.input :name, placeholder: "Name" %>
          <%= f.input :photo, as: :file %>
          <%= f.input :description, placeholder: "Description" %>
          <%= f.input :address, placeholder: "Address" %>
          <%= f.input :price, placeholder: "Price" %>
          <%= f.input :brand, prompt: "Please select ...", :collection => ['Weber', 'Traeger', 'Big Green Egg', 'Napoleon', 'Yoder Smokers', 'Beefeaters', 'Other'] %>
          <%= f.input :fuel_type, prompt: "Please select ...", :collection => ['Charcoal', 'Electric', 'Gas']%>
          <%= f.input :grill_size, prompt: "Please select ...", :collection => ["2 people", "4 people", "6 people", "8 people", "10+ people"] %>
          <%= f.input :pick_up, prompt: "Please select ..." %>
          <%= f.input :delivery, prompt: "Please select ..." %>
          <%= f.submit "Add BBQ", class: "btn btn-primary form-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bbqs/show.html.erb
<div class="page-body">
  <div class="showpage-container">
    <div class="content">
      <div class="bbq-image">
        <% if @bbq.photo.attached? %>
          <%= cl_image_tag @bbq.photo.key, height: 430, width: 1000, crop: :auto, alt: "#{@bbq.name} image"%>
        <% else %>
          <%= image_tag "bbq.png", height: 430, width: 1000, crop: :auto, alt: "#{@bbq.name} image"%>
        <% end %>
      </div>

      <div class="details-and-form">
        <div class="bbq-details">
          <h1><%= @bbq.name %></h1>
          <h4><%= @bbq.address %></h4>
          <p><%= @bbq.description %></p>


        <div class="product-details">
          <h3>Details:</h3>
          <div class="row d-flex">
            <div class="product-detail col-4 flex-column">
              <strong>Brand:</strong>
              <strong>Fuel Type:</strong>
              <strong>Grill Size:</strong>
            </div>
            <div class="product-detail col-4 flex-column">
              <span><%= @bbq.brand %></span>
              <span><%= @bbq.fuel_type %></span>
              <span><%= @bbq.grill_size %></span>
            </div>
          </div>
        </div>


          <div class="map-container">
            <h3>Map:</h3>
            <div style="width: 100%; height: 400px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>
        </div>

        <div class="booking-form" data-controller="booking-details" data-bbq-price="<%= @bbq.price %>" data-booking-start="<%= @booking.start_date %>" data-booking-end="<%= @booking.end_date %>">
          <h3>Book BBQ</h3>
          <div class="booking-item">
            <p><strong>Number of days: </strong></p>
            <p data-booking-details-target="displayedDays">-</p>
          </div>
          <div class="booking-item"><p><strong>Price / day: </strong></p><p><%= number_to_currency(@bbq.price, unit: "£", precision: 2) %></p></div>
          <div class="booking-item">
            <p><strong>Total Price: </strong></p>
            <p data-booking-details-target="displayedPrice">-</p>
          </div>
          <div class="show-book-fields">
            <%= simple_form_for [@bbq, @booking] do |f| %>
              <%= f.input :start_date,
                      as: :string,
                      input_html: { data: { controller: "datepicker", booking_details_target: "startDate", action: "change->booking-details#updateDetails" } },
                      class: "booking-field" %>
              <%= f.input :end_date,
                      as: :string,
                      input_html: { data: { controller: "datepicker", booking_details_target: "endDate", action: "change->booking-details#updateDetails" } },
                      class: "booking-field" %>
              <%= f.submit "Book", class: "btn btn-primary booking-button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_marker.html.erb
<%= image_tag "fire.png", height: 30, alt: "Fire" %>

app/views/bookings/edit.html.erb
<%# <a href="<%= bbq_path(booking.bbq, booking: { start_date: booking.start_date, end_date: booking.end_date }) %>


<div class="page-body">
  <div class="showpage-container">
    <div class="content">
      <div class="bbq-image">
        <% if @booking.bbq.photo.attached? %>
          <%= cl_image_tag @booking.bbq.photo.key, height: 430, width: 1000, crop: :auto, alt: "#{@booking.bbq.name} image"%>
        <% else %>
          <%= image_tag "bbq.png", height: 430, width: 1000, crop: :auto, alt: "#{@booking.bbq.name} image"%>
        <% end %>
      </div>

      <div class="details-and-form">
        <div class="bbq-details">
          <h1><%= @booking.bbq.name %></h1>
          <h4><%= @booking.bbq.address %></h4>
          <p><%= @booking.bbq.description %></p>


        <div class="product-details">
          <h3>Details:</h3>
          <div class="row d-flex">
            <div class="product-detail col-4 flex-column">
              <strong>Brand:</strong>
              <strong>Fuel Type:</strong>
              <strong>Grill Size:</strong>
            </div>
            <div class="product-detail col-4 flex-column">
              <span><%= @booking.bbq.brand %></span>
              <span><%= @booking.bbq.fuel_type %></span>
              <span><%= @booking.bbq.grill_size %></span>
            </div>
          </div>
        </div>


          <div class="map-container">
            <h3>Map:</h3>
            <div style="width: 100%; height: 400px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
          </div>
        </div>

        <div class="booking-form" data-controller="booking-details" data-bbq-price="<%= @booking.bbq.price %>" data-booking-start="<%= @booking.start_date %>" data-booking-end="<%= @booking.end_date %>">
          <h3>Update Booking</h3>
          <div class="booking-item">
            <p><strong>Number of days: </strong></p>
            <p data-booking-details-target="displayedDays">-</p>
          </div>
          <div class="booking-item"><p><strong>Price / day: </strong></p><p><%= number_to_currency(@booking.bbq.price, unit: "£", precision: 2) %></p></div>
          <div class="booking-item">
            <p><strong>Total Price: </strong></p>
            <p data-booking-details-target="displayedPrice">-</p>
          </div>

          <%= simple_form_for [@booking.bbq, @booking], method: :patch do |f| %>
            <%= f.input :start_date,
                    as: :string,
                    input_html: { data: { controller: "datepicker", booking_details_target: "startDate", action: "change->booking-details#updateDetails" } },
                    class: "booking-field" %>
            <%= f.input :end_date,
                    as: :string,
                    input_html: { data: { controller: "datepicker", booking_details_target: "endDate", action: "change->booking-details#updateDetails" } },
                    class: "booking-field" %>
            <%= f.submit "Update", class: "btn btn-primary booking-button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="page-body">
  <div class="my-bbqs-bookings-container">
    <div class="my-bbqs-bookings-headers">
      <h1>My Bookings
        <% if current_user.bookings.nil? %>
          <%= "(0)" %>
        <% else %>
          <%= "(#{current_user.bookings.count})" %>
        <% end %>
      </h1>

      <%= link_to "New Booking", root_path, class: "btn btn-primary" %>
    </div>

    <div class="my-bookings">
      <% current_user.bookings.order(:start_date).each do |booking| %>
        <a href="<%= edit_bbq_booking_path(booking.bbq_id, booking.id) %>" class="cards-horizontal-link">
          <div class="cards-horizontal">
            <div class="image-height-override">
              <% if booking.bbq.photo.attached? %>
                <%= cl_image_tag booking.bbq.photo.key, height: 430, width: 1000, crop: :auto, alt: "#{booking.bbq.name} image", class: "cards-horizontal-image" %>
              <% else %>
                <%= image_tag "bbq.png", height: 430, width: 1000, crop: :auto, alt: "#{booking.bbq.name} image", class: "cards-horizontal-image" %>
              <% end %>
            </div>
            <div class="cards-horizontal-card-info">
              <h4><%= "#{booking.start_date.strftime('%-d %b')} - #{booking.end_date.strftime('%-d %b %Y')}" %></h4>
              <h3><%= booking.bbq.name %></h3>
              <p><%= booking.bbq.address %></p>
              <p class="truncate-text"><%= truncate(booking.bbq.description, length: 115) %></p>
              <div>
                <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                  <i class="fa-solid fa-trash booking-icon"></i>
                <% end %>
              </div>
            </div>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>inside new booking page!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmokeNGo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "/shared/navbar" %>
    <div class="body-container">
    <%= yield %>
    </div>
    <p class="notice mb-0"><%= notice %></p>
    <p class="alert mb-0"><%= alert %></p>
<%# render the footer partial "_footer.html.erb" file from "shared" folder  everywhere on the app but on landing page%>
    <% unless action_name == "home" %>
       <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="landing_container">
  <div class="container d-flex justify-content-center flex-column ">
    <h1 class = "text-center mt-5" >Grill. Chill. Rent at will.</h1>
    <div class="row container w-100 mx-auto my-5">
      <%= simple_form_for(@booking, url: bbqs_path, method: :get) do |f| %>
        <div class="d-flex align-items-center justify-content-between border rounded  bg-white" style="height: 45px; width: 750px">
          <div class="search-date d-flex justify-content-center ">
            <%= f.input :start_date,
                        as: :string,
                        required: false,
                        placeholder: "Select date",
                        input_html: {
                          data: { controller: "datepicker" },
                          class: "border-0 text-center w-100 date-input ",
                          },
                        label_html: {
                          class: "border-0 text-center ms-1 w-100 mb-0 ",
                          } %>
          </div>
          <div class="search-date d-flex justify-content-center">
            <%= f.input :end_date,
                        as: :string,
                        placeholder: "Select date",
                        required: false,
                        input_html: {
                          data: { controller: "datepicker" },
                            class: "border-0 text-center w-100"
                          },
                          label_html: {
                            class: "border-0 text-center ms-1 w-100 mb-0",
                          }
                          %>
          </div>
          <button type="submit" class="btn border-0 d-flex align-items-center date-sub">
            <i class="fas fa-search"></i> <!-- Font Awesome Search Icon -->
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%# <div class="container mx-auto d-flex justify-content-center flex-column mt-5 width">
  <div>
    <div class="row border-bottom border-secondary text-left mb-4">
      <h2>Today's Hot Grills</h2>
    </div>
    <%= render "shared/cards" %>
  <%# </div> %>
<%# </div> %>

app/views/pages/my_bbqs.html.erb
<div class="page-body">
  <div class="my-bbqs-bookings-container">
    <div class="my-bbqs-bookings-headers">
      <h1>My BBQs
        <% if current_user.bbqs.nil? %>
          <%= "(0)" %>
        <% else %>
          <%= "(#{current_user.bbqs.count})" %>
        <% end %>
      </h1>

      <%= link_to "Add BBQ", new_bbq_path, class: "btn btn-primary" %>
    </div>

    <%= render "shared/cards" %>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="index-cards-container">
  <div class="row g-3">
    <% @bbqs.each do |bbq|  %>
      <div class="col-md-4">
        <%= link_to bbq_path(bbq, booking: { start_date: params.dig("booking", "start_date"), end_date: params.dig("booking", "end_date") }), class: 'card-link' do %>
          <div class="card card-shadow">
            <% if bbq.photo.attached? %>
              <%= cl_image_tag bbq.photo.key, class: 'img-top img-fit card-img-top', alt: "#{bbq.name} image"%>
            <% else %>
              <%= image_tag "bbq.png", class: 'img-top img-fit card-img-top', alt: "#{bbq.name} image"%>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"> <%= bbq.name %> </h5>
              <p class="card-text truncate-text-lines"> <%= bbq.description %> </p>
              <div class="container">
                <div class="row align-items-center mt-3">
                  <p class="card-text col-md-5 price-text p-0"><%= "#{number_to_currency(bbq.price, unit: "£", precision: 2)} / day" %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <%# <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div> %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-smoke-n-go sticky-top">
  <div class="container-fluid">
    <h1> <%= link_to "Smoke 'n Go", root_path, class: "navbar-brand" %></h1>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My BBQs", my_bbqs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "profile.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>